language: ruby
sudo: false
cache:
  - ccache
  - bundler

before_install: gem install bundler -v 1.13.6

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - ruby-head
  - rbx-2

matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: ruby-head
    - rvm: rbx-2
  fast_finish: true
